AllCops:
  NewCops: disable
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - spec/**/*
    - slack-notifier.gemspec

# Naming ------------------------------------

Naming/FileName:
  Exclude:
    - lib/slack-notifier.rb
    - Gemfile

Naming/MemoizedInstanceVariableName:
  Enabled: false

# Style ------------------------------------

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - lib/slack-notifier/util/link_formatter.rb

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/RaiseArgs:
  Enabled: false

# Layout ----------------------------------

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/DotPosition:
  EnforcedStyle: leading
  
Layout/LineLength:
  Max: 200

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# Metrics ----------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

# Bundler ----------------------------------

Bundler/OrderedGems:
  Enabled: false

# Gemspec ----------------------------------

Gemspec/RequiredRubyVersion:
  Enabled: false

# Lint -------------------------------------

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
